# -*- coding: utf-8 -*-

fHandle = open("../plugin.video.cntv-live/resources/epg.m3u", "w")
fHandle.write("#EXTM3U\n")

def addStream(channelID, channelName):
	fHandle.write('#EXTINF:-1 tvg-id="{0}" tvg-name="{1}" group-title="{2}",{3}\n'.format(channelID, channelName.replace(" ", "_"), group, channelName))
	fHandle.write('special://temp/\n') #IPTV doesn't support plugin:// URIs for now.

group = "央视频道"
addStream("cctv1", "CCTV-1 综合")
addStream("cctv2", "CCTV-2 财经")
addStream("cctv3", "CCTV-3 综艺")
addStream("cctv4", "CCTV-4 (亚洲)")
addStream("cctveurope", "CCTV-4 (欧洲)")
addStream("cctvamerica", "CCTV-4 (美洲)")
addStream("cctv5", "CCTV-5 体育")
addStream("cctv6", "CCTV-6 电影")
addStream("cctv7", "CCTV-7 军事 农业")
addStream("cctv8", "CCTV-8 电视剧")
addStream("cctvjilu", "CCTV-9 纪录")
addStream("cctvdoc", "CCTV-9 纪录(英)")
addStream("cctv10", "CCTV-10 科教")
addStream("cctv11", "CCTV-11 戏曲")
addStream("cctv12", "CCTV-12 社会与法")
addStream("cctv13", "CCTV-13 新闻")
addStream("cctvchild", "CCTV-14 少儿")
addStream("cctv15", "CCTV-15 音乐")
addStream("cctv9", "CCTV-NEWS")
addStream("cctv5plus", "CCTV体育赛事")

group = "卫视频道"
addStream("anhui", "安徽卫视")
addStream("btv1", "北京卫视")
addStream("bingtuan", "兵团卫视")
addStream("chongqing", "重庆卫视")
addStream("dongfang", "东方卫视")
addStream("dongnan", "东南卫视")
addStream("gansu", "甘肃卫视")
addStream("guangdong", "广东卫视")
addStream("guangxi", "广西卫视")
addStream("guizhou", "贵州卫视")
addStream("hebei", "河北卫视")
addStream("henan", "河南卫视")
addStream("heilongjiang", "黑龙江卫视")
addStream("hubei", "湖北卫视")
addStream("jilin", "吉林卫视")
addStream("jiangxi", "江西卫视")
addStream("kangba", "康巴卫视")
addStream("liaoning", "辽宁卫视")
addStream("travel", "旅游卫视")
addStream("neimenggu", "内蒙古卫视")
addStream("ningxia", "宁夏卫视")
addStream("qinghai", "青海卫视")
addStream("shandong", "山东卫视")
addStream("sdetv", "山东教育台")
addStream("shenzhen", "深圳卫视")
addStream("shan1xi", "山西卫视")
addStream("shan3xi", "陕西卫视")
addStream("shenzhen", "深圳卫视")
addStream("sichuan", "四川卫视")
addStream("tianjin", "天津卫视")
addStream("xizang", "西藏卫视")
addStream("xiamen", "厦门卫视")
addStream("xianggangweishi", "香港卫视")
addStream("xinjiang", "新疆卫视")
addStream("yanbian", "延边卫视")
addStream("yunnan", "云南卫视")
addStream("zhejiang", "浙江卫视")

fHandle.close()
